name: PR

on:
  pull_request:
    branches:
      - main
      - next

run-name: "PR - ${{ github.event.pull_request.title }}"

jobs:
  build:
    uses: vfourny/.github/.github/workflows/build.yml@main
    with:
      is_build: true
